# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PlaceResponse.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'PlaceResponse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Shared_pb2 as Shared__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13PlaceResponse.proto\x12\tgeocoding\x1a\x0cShared.proto\"\xec\x05\n\rPlaceResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12,\n\x0crequest_type\x18\x02 \x01(\x0e\x32\x16.geocoding.RequestType\x12\x18\n\x10\x64isplay_language\x18\x05 \x03(\t\x12\x38\n\x0bmaps_result\x18\n \x01(\x0b\x32#.geocoding.PlaceResponse.MapsResult\x1ak\n\nMapsResult\x12.\n\x0bresult_type\x18\x01 \x01(\x0e\x32\x19.geocoding.MapsResultType\x12-\n\x05place\x18\x02 \x01(\x0b\x32\x1e.geocoding.PlaceResponse.Place\x1aL\n\x05Place\x12\x0c\n\x04muid\x18\x01 \x01(\x04\x12\x35\n\tcomponent\x18\x04 \x03(\x0b\x32\".geocoding.PlaceResponse.Component\x1ak\n\tComponent\x12&\n\x04type\x18\x01 \x01(\x0e\x32\x18.geocoding.ComponentType\x12\x36\n\x05value\x18\x08 \x03(\x0b\x32\'.geocoding.PlaceResponse.ComponentValue\x1aP\n\x0e\x43omponentValue\x12>\n\x0e\x61\x64\x64ress_object\x18\x01 \x01(\x0b\x32&.geocoding.PlaceResponse.AddressObject\x1aP\n\rAddressObject\x12?\n\x0e\x61\x64\x64ress_object\x18\x01 \x01(\x0b\x32\'.geocoding.PlaceResponse.AddressObject_\x1a@\n\x0e\x41\x64\x64ressObject_\x12.\n\x05place\x18\x65 \x01(\x0b\x32\x1f.geocoding.PlaceResponse.Place_\x1a;\n\x06Place_\x12\x0c\n\x04name\x18\x01 \x01(\t\x12#\n\x07\x61\x64\x64ress\x18\x02 \x01(\x0b\x32\x12.geocoding.Addressb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlaceResponse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLACERESPONSE']._serialized_start=49
  _globals['_PLACERESPONSE']._serialized_end=797
  _globals['_PLACERESPONSE_MAPSRESULT']._serialized_start=212
  _globals['_PLACERESPONSE_MAPSRESULT']._serialized_end=319
  _globals['_PLACERESPONSE_PLACE']._serialized_start=321
  _globals['_PLACERESPONSE_PLACE']._serialized_end=397
  _globals['_PLACERESPONSE_COMPONENT']._serialized_start=399
  _globals['_PLACERESPONSE_COMPONENT']._serialized_end=506
  _globals['_PLACERESPONSE_COMPONENTVALUE']._serialized_start=508
  _globals['_PLACERESPONSE_COMPONENTVALUE']._serialized_end=588
  _globals['_PLACERESPONSE_ADDRESSOBJECT']._serialized_start=590
  _globals['_PLACERESPONSE_ADDRESSOBJECT']._serialized_end=670
  _globals['_PLACERESPONSE_ADDRESSOBJECT_']._serialized_start=672
  _globals['_PLACERESPONSE_ADDRESSOBJECT_']._serialized_end=736
  _globals['_PLACERESPONSE_PLACE_']._serialized_start=738
  _globals['_PLACERESPONSE_PLACE_']._serialized_end=797
# @@protoc_insertion_point(module_scope)
